version: '3'

services:
  mysql:
    image: mysql:5.6.47
    volumes:
      - ./database/dump:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    networks:
      - backend

  redis:
    image: redis
    expose:
      - 6379
    ports:
      - 6379:6379
    networks:
      - backend

  app:
    build:
      context: .
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    networks:
      - backend

networks:
  backend:
    external: false
