version: '3'
services:
  mysql:
    image: mysql:5.6.47
    volumes:
      - ./database/dump:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
  redis:
    image: redis
    expose:
      - 6379
    ports:
      - 6379:6379
  app:
    image: cardenasrjl/emem:tagname
    ports:
      - "8080:8080"
      - "8082:8082"
    depends_on:
      - mysql