// Code generated by protoc-gen-go. DO NOT EDIT.
// source: volume_service.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//entry
type Volume struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64                `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title                string               `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description          string               `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Volume) Reset()         { *m = Volume{} }
func (m *Volume) String() string { return proto.CompactTextString(m) }
func (*Volume) ProtoMessage()    {}
func (*Volume) Descriptor() ([]byte, []int) {
	return fileDescriptor_4eb8bec198281e5c, []int{0}
}

func (m *Volume) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Volume.Unmarshal(m, b)
}
func (m *Volume) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Volume.Marshal(b, m, deterministic)
}
func (m *Volume) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Volume.Merge(m, src)
}
func (m *Volume) XXX_Size() int {
	return xxx_messageInfo_Volume.Size(m)
}
func (m *Volume) XXX_DiscardUnknown() {
	xxx_messageInfo_Volume.DiscardUnknown(m)
}

var xxx_messageInfo_Volume proto.InternalMessageInfo

func (m *Volume) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Volume) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Volume) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Volume) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Volume) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Volume) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

//new entry
type NewVolumeRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewVolumeRequest) Reset()         { *m = NewVolumeRequest{} }
func (m *NewVolumeRequest) String() string { return proto.CompactTextString(m) }
func (*NewVolumeRequest) ProtoMessage()    {}
func (*NewVolumeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4eb8bec198281e5c, []int{1}
}

func (m *NewVolumeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewVolumeRequest.Unmarshal(m, b)
}
func (m *NewVolumeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewVolumeRequest.Marshal(b, m, deterministic)
}
func (m *NewVolumeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewVolumeRequest.Merge(m, src)
}
func (m *NewVolumeRequest) XXX_Size() int {
	return xxx_messageInfo_NewVolumeRequest.Size(m)
}
func (m *NewVolumeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewVolumeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewVolumeRequest proto.InternalMessageInfo

func (m *NewVolumeRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *NewVolumeRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *NewVolumeRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type NewVolumeResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewVolumeResponse) Reset()         { *m = NewVolumeResponse{} }
func (m *NewVolumeResponse) String() string { return proto.CompactTextString(m) }
func (*NewVolumeResponse) ProtoMessage()    {}
func (*NewVolumeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4eb8bec198281e5c, []int{2}
}

func (m *NewVolumeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewVolumeResponse.Unmarshal(m, b)
}
func (m *NewVolumeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewVolumeResponse.Marshal(b, m, deterministic)
}
func (m *NewVolumeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewVolumeResponse.Merge(m, src)
}
func (m *NewVolumeResponse) XXX_Size() int {
	return xxx_messageInfo_NewVolumeResponse.Size(m)
}
func (m *NewVolumeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewVolumeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewVolumeResponse proto.InternalMessageInfo

func (m *NewVolumeResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

//get volumes
type GetVolumesRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVolumesRequest) Reset()         { *m = GetVolumesRequest{} }
func (m *GetVolumesRequest) String() string { return proto.CompactTextString(m) }
func (*GetVolumesRequest) ProtoMessage()    {}
func (*GetVolumesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4eb8bec198281e5c, []int{3}
}

func (m *GetVolumesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVolumesRequest.Unmarshal(m, b)
}
func (m *GetVolumesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVolumesRequest.Marshal(b, m, deterministic)
}
func (m *GetVolumesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVolumesRequest.Merge(m, src)
}
func (m *GetVolumesRequest) XXX_Size() int {
	return xxx_messageInfo_GetVolumesRequest.Size(m)
}
func (m *GetVolumesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVolumesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetVolumesRequest proto.InternalMessageInfo

func (m *GetVolumesRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetVolumesResponse struct {
	Volumes              []*Volume `protobuf:"bytes,1,rep,name=volumes,proto3" json:"volumes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetVolumesResponse) Reset()         { *m = GetVolumesResponse{} }
func (m *GetVolumesResponse) String() string { return proto.CompactTextString(m) }
func (*GetVolumesResponse) ProtoMessage()    {}
func (*GetVolumesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4eb8bec198281e5c, []int{4}
}

func (m *GetVolumesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVolumesResponse.Unmarshal(m, b)
}
func (m *GetVolumesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVolumesResponse.Marshal(b, m, deterministic)
}
func (m *GetVolumesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVolumesResponse.Merge(m, src)
}
func (m *GetVolumesResponse) XXX_Size() int {
	return xxx_messageInfo_GetVolumesResponse.Size(m)
}
func (m *GetVolumesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVolumesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetVolumesResponse proto.InternalMessageInfo

func (m *GetVolumesResponse) GetVolumes() []*Volume {
	if m != nil {
		return m.Volumes
	}
	return nil
}

//get volumes
type GetVolumeRequest struct {
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVolumeRequest) Reset()         { *m = GetVolumeRequest{} }
func (m *GetVolumeRequest) String() string { return proto.CompactTextString(m) }
func (*GetVolumeRequest) ProtoMessage()    {}
func (*GetVolumeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4eb8bec198281e5c, []int{5}
}

func (m *GetVolumeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVolumeRequest.Unmarshal(m, b)
}
func (m *GetVolumeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVolumeRequest.Marshal(b, m, deterministic)
}
func (m *GetVolumeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVolumeRequest.Merge(m, src)
}
func (m *GetVolumeRequest) XXX_Size() int {
	return xxx_messageInfo_GetVolumeRequest.Size(m)
}
func (m *GetVolumeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVolumeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetVolumeRequest proto.InternalMessageInfo

func (m *GetVolumeRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetVolumeRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetVolumeResponse struct {
	Volume               *Volume  `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVolumeResponse) Reset()         { *m = GetVolumeResponse{} }
func (m *GetVolumeResponse) String() string { return proto.CompactTextString(m) }
func (*GetVolumeResponse) ProtoMessage()    {}
func (*GetVolumeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4eb8bec198281e5c, []int{6}
}

func (m *GetVolumeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVolumeResponse.Unmarshal(m, b)
}
func (m *GetVolumeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVolumeResponse.Marshal(b, m, deterministic)
}
func (m *GetVolumeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVolumeResponse.Merge(m, src)
}
func (m *GetVolumeResponse) XXX_Size() int {
	return xxx_messageInfo_GetVolumeResponse.Size(m)
}
func (m *GetVolumeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVolumeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetVolumeResponse proto.InternalMessageInfo

func (m *GetVolumeResponse) GetVolume() *Volume {
	if m != nil {
		return m.Volume
	}
	return nil
}

//delete entry
type DeleteVolumeRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteVolumeRequest) Reset()         { *m = DeleteVolumeRequest{} }
func (m *DeleteVolumeRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteVolumeRequest) ProtoMessage()    {}
func (*DeleteVolumeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4eb8bec198281e5c, []int{7}
}

func (m *DeleteVolumeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteVolumeRequest.Unmarshal(m, b)
}
func (m *DeleteVolumeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteVolumeRequest.Marshal(b, m, deterministic)
}
func (m *DeleteVolumeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteVolumeRequest.Merge(m, src)
}
func (m *DeleteVolumeRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteVolumeRequest.Size(m)
}
func (m *DeleteVolumeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteVolumeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteVolumeRequest proto.InternalMessageInfo

func (m *DeleteVolumeRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteResponseResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponseResponse) Reset()         { *m = DeleteResponseResponse{} }
func (m *DeleteResponseResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponseResponse) ProtoMessage()    {}
func (*DeleteResponseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4eb8bec198281e5c, []int{8}
}

func (m *DeleteResponseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponseResponse.Unmarshal(m, b)
}
func (m *DeleteResponseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponseResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponseResponse.Merge(m, src)
}
func (m *DeleteResponseResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponseResponse.Size(m)
}
func (m *DeleteResponseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponseResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Volume)(nil), "v1.Volume")
	proto.RegisterType((*NewVolumeRequest)(nil), "v1.NewVolumeRequest")
	proto.RegisterType((*NewVolumeResponse)(nil), "v1.NewVolumeResponse")
	proto.RegisterType((*GetVolumesRequest)(nil), "v1.GetVolumesRequest")
	proto.RegisterType((*GetVolumesResponse)(nil), "v1.GetVolumesResponse")
	proto.RegisterType((*GetVolumeRequest)(nil), "v1.GetVolumeRequest")
	proto.RegisterType((*GetVolumeResponse)(nil), "v1.GetVolumeResponse")
	proto.RegisterType((*DeleteVolumeRequest)(nil), "v1.DeleteVolumeRequest")
	proto.RegisterType((*DeleteResponseResponse)(nil), "v1.DeleteResponseResponse")
}

func init() { proto.RegisterFile("volume_service.proto", fileDescriptor_4eb8bec198281e5c) }

var fileDescriptor_4eb8bec198281e5c = []byte{
	// 479 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0x5d, 0x8b, 0xd3, 0x40,
	0x14, 0x25, 0xa9, 0xdb, 0xa5, 0xb7, 0xae, 0x74, 0x67, 0xbb, 0xbb, 0x21, 0x08, 0x86, 0x51, 0xa1,
	0xc8, 0x6e, 0x42, 0xeb, 0x83, 0xa8, 0x4f, 0x0b, 0x82, 0xf8, 0x22, 0x12, 0xc5, 0x37, 0x29, 0xd9,
	0xe4, 0x1a, 0x06, 0xda, 0x4c, 0xcc, 0x4c, 0xb2, 0x0f, 0xe2, 0x8b, 0x7f, 0x41, 0xff, 0x99, 0x3f,
	0xc0, 0x17, 0x7f, 0x88, 0x74, 0x3e, 0xda, 0xb4, 0xa9, 0xee, 0xd3, 0x30, 0xf7, 0x9e, 0x7b, 0xce,
	0x3d, 0x27, 0x13, 0x18, 0x37, 0x7c, 0x51, 0x2f, 0x71, 0x2e, 0xb0, 0x6a, 0x58, 0x8a, 0x61, 0x59,
	0x71, 0xc9, 0x89, 0xdb, 0x4c, 0xfd, 0x07, 0x39, 0xe7, 0xf9, 0x02, 0x23, 0x55, 0xb9, 0xae, 0x3f,
	0x47, 0x92, 0x2d, 0x51, 0xc8, 0x64, 0x59, 0x6a, 0x90, 0x7f, 0xdf, 0x00, 0x92, 0x92, 0x45, 0x49,
	0x51, 0x70, 0x99, 0x48, 0xc6, 0x0b, 0x61, 0xba, 0x17, 0xea, 0x48, 0x2f, 0x73, 0x2c, 0x2e, 0xc5,
	0x4d, 0x92, 0xe7, 0x58, 0x45, 0xbc, 0x54, 0x88, 0x2e, 0x9a, 0xfe, 0x76, 0xa0, 0xff, 0x51, 0x6d,
	0x42, 0xee, 0x81, 0xcb, 0x32, 0xcf, 0x09, 0x9c, 0x49, 0x2f, 0x76, 0x59, 0x46, 0xce, 0xe1, 0xb0,
	0x16, 0x58, 0xcd, 0x59, 0xe6, 0xb9, 0xaa, 0xd8, 0x5f, 0x5d, 0xdf, 0x64, 0x64, 0x0c, 0x07, 0x92,
	0xc9, 0x05, 0x7a, 0xbd, 0xc0, 0x99, 0x0c, 0x62, 0x7d, 0x21, 0x01, 0x0c, 0x33, 0x14, 0x69, 0xc5,
	0x94, 0x96, 0x77, 0x47, 0xf5, 0xda, 0x25, 0xf2, 0x1c, 0x20, 0xad, 0x30, 0x91, 0x98, 0xcd, 0x13,
	0xe9, 0x1d, 0x04, 0xce, 0x64, 0x38, 0xf3, 0x43, 0x6d, 0x26, 0xb4, 0x6e, 0xc3, 0x0f, 0xd6, 0x6d,
	0x3c, 0x30, 0xe8, 0x2b, 0xb9, 0x1a, 0xad, 0xcb, 0xcc, 0x8e, 0xf6, 0x6f, 0x1f, 0x35, 0xe8, 0x2b,
	0x49, 0x53, 0x18, 0xbd, 0xc5, 0x1b, 0xed, 0x31, 0xc6, 0x2f, 0x35, 0x0a, 0xd9, 0xb6, 0xe6, 0xa8,
	0x3d, 0x3b, 0xd6, 0xdc, 0xff, 0x58, 0xeb, 0x75, 0xac, 0xd1, 0x87, 0x70, 0xdc, 0x12, 0x11, 0x25,
	0x2f, 0x44, 0x27, 0x50, 0x7a, 0x01, 0xc7, 0xaf, 0x51, 0x6a, 0x90, 0xf8, 0xc7, 0x2a, 0xeb, 0x94,
	0xe9, 0x0b, 0x20, 0x6d, 0xb4, 0xe1, 0x7c, 0x04, 0x87, 0xfa, 0xe1, 0x08, 0xcf, 0x09, 0x7a, 0x93,
	0xe1, 0x0c, 0xc2, 0x66, 0x1a, 0x1a, 0x61, 0xdb, 0xa2, 0x2f, 0x61, 0xb4, 0x9e, 0xb5, 0x42, 0x7a,
	0x1b, 0x77, 0xdf, 0xe7, 0xdd, 0x16, 0x7e, 0xd6, 0x5a, 0x73, 0xad, 0x4b, 0xa1, 0xaf, 0xc9, 0x15,
	0x78, 0x5b, 0xd6, 0x74, 0xe8, 0x63, 0x38, 0x79, 0x85, 0x0b, 0x94, 0xb8, 0x4f, 0x78, 0x13, 0x83,
	0x07, 0x67, 0x1a, 0x66, 0xc9, 0xed, 0x39, 0xfb, 0xe9, 0xc2, 0x91, 0x9e, 0x7d, 0xaf, 0xff, 0x0a,
	0xf2, 0x0e, 0x60, 0x13, 0x02, 0x39, 0x5d, 0x89, 0x76, 0x22, 0xf4, 0xcf, 0x76, 0xcb, 0x9a, 0x8e,
	0x9e, 0x7c, 0xff, 0xf5, 0xe7, 0x87, 0x7b, 0x44, 0x86, 0x51, 0x33, 0x8d, 0x4c, 0x34, 0x24, 0x86,
	0xc1, 0x1a, 0x4a, 0xc6, 0x5b, 0x93, 0x96, 0xef, 0x74, 0xa7, 0x6a, 0xe8, 0x3c, 0x45, 0x47, 0xc8,
	0xa8, 0x45, 0x17, 0x7d, 0x65, 0xd9, 0x37, 0xf2, 0x09, 0xee, 0xb6, 0x8d, 0x93, 0xf3, 0x15, 0xc1,
	0x9e, 0x28, 0x7c, 0x7f, 0xd3, 0xd8, 0x35, 0x6f, 0xe9, 0x9f, 0x74, 0xe8, 0xaf, 0xfb, 0xea, 0x81,
	0x3f, 0xfd, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xfe, 0x98, 0xdb, 0xa1, 0x33, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// VolumeServiceClient is the client API for VolumeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VolumeServiceClient interface {
	//Get Volumes
	GetVolumes(ctx context.Context, in *GetVolumesRequest, opts ...grpc.CallOption) (*GetVolumesResponse, error)
	//Get Volume
	GetVolume(ctx context.Context, in *GetVolumeRequest, opts ...grpc.CallOption) (*GetVolumeResponse, error)
	//Delete Volume
	DeleteVolume(ctx context.Context, in *DeleteVolumeRequest, opts ...grpc.CallOption) (*DeleteResponseResponse, error)
}

type volumeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVolumeServiceClient(cc grpc.ClientConnInterface) VolumeServiceClient {
	return &volumeServiceClient{cc}
}

func (c *volumeServiceClient) GetVolumes(ctx context.Context, in *GetVolumesRequest, opts ...grpc.CallOption) (*GetVolumesResponse, error) {
	out := new(GetVolumesResponse)
	err := c.cc.Invoke(ctx, "/v1.VolumeService/GetVolumes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeServiceClient) GetVolume(ctx context.Context, in *GetVolumeRequest, opts ...grpc.CallOption) (*GetVolumeResponse, error) {
	out := new(GetVolumeResponse)
	err := c.cc.Invoke(ctx, "/v1.VolumeService/GetVolume", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeServiceClient) DeleteVolume(ctx context.Context, in *DeleteVolumeRequest, opts ...grpc.CallOption) (*DeleteResponseResponse, error) {
	out := new(DeleteResponseResponse)
	err := c.cc.Invoke(ctx, "/v1.VolumeService/DeleteVolume", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VolumeServiceServer is the server API for VolumeService service.
type VolumeServiceServer interface {
	//Get Volumes
	GetVolumes(context.Context, *GetVolumesRequest) (*GetVolumesResponse, error)
	//Get Volume
	GetVolume(context.Context, *GetVolumeRequest) (*GetVolumeResponse, error)
	//Delete Volume
	DeleteVolume(context.Context, *DeleteVolumeRequest) (*DeleteResponseResponse, error)
}

// UnimplementedVolumeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedVolumeServiceServer struct {
}

func (*UnimplementedVolumeServiceServer) GetVolumes(ctx context.Context, req *GetVolumesRequest) (*GetVolumesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVolumes not implemented")
}
func (*UnimplementedVolumeServiceServer) GetVolume(ctx context.Context, req *GetVolumeRequest) (*GetVolumeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVolume not implemented")
}
func (*UnimplementedVolumeServiceServer) DeleteVolume(ctx context.Context, req *DeleteVolumeRequest) (*DeleteResponseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteVolume not implemented")
}

func RegisterVolumeServiceServer(s *grpc.Server, srv VolumeServiceServer) {
	s.RegisterService(&_VolumeService_serviceDesc, srv)
}

func _VolumeService_GetVolumes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVolumesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServiceServer).GetVolumes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.VolumeService/GetVolumes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServiceServer).GetVolumes(ctx, req.(*GetVolumesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolumeService_GetVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServiceServer).GetVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.VolumeService/GetVolume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServiceServer).GetVolume(ctx, req.(*GetVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolumeService_DeleteVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServiceServer).DeleteVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.VolumeService/DeleteVolume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServiceServer).DeleteVolume(ctx, req.(*DeleteVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VolumeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.VolumeService",
	HandlerType: (*VolumeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVolumes",
			Handler:    _VolumeService_GetVolumes_Handler,
		},
		{
			MethodName: "GetVolume",
			Handler:    _VolumeService_GetVolume_Handler,
		},
		{
			MethodName: "DeleteVolume",
			Handler:    _VolumeService_DeleteVolume_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "volume_service.proto",
}
